services:
  app: # 나중에 베포용에 써먹을 용도,,
    image: hrr/backend
    build: .
    platform: linux/amd64
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${LOCAL_DB_URL_DOCKER}
      SPRING_DATASOURCE_USERNAME: ${LOCAL_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${LOCAL_DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis-server # Redis 서비스 이름(컨테이너 간 통신에 사용)
      SPRING_DATA_REDIS_PORT: 6379

      MODEL_API_URL: http://model-api:8000/recommend

    depends_on:
      db:
        condition: service_healthy
      model-api:
        condition: service_started

  db:
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD" ]
      timeout: 20s
      retries: 5
      interval: 5s
      start_period: 20s
    image: mysql:latest
    container_name: hrr-local_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD : ${LOCAL_DB_PASSWORD}
      MYSQL_DATABASE : hrr-server
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password

    volumes:
      - db-data:/var/lib/mysql

  redis-server:
    image: redis:7.4.2-alpine
    container_name: hrr_redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data    # 영속성 유지

  model-api:
    build: ../Hrr-model/hrr-RecSys
    image: hrr/model-api
    container_name: hrr-model-api
    platform: linux/amd64
    ports:
      - "8000:8000"         # 필요 없으면 빼도 됨 (외부에서 직접 안 쏠 거면)
    env_file:
      - .env                # 모델 쪽에서 쓸 환경변수 있으면
    restart: always

volumes:
  db-data:
  redis_data:
