spring:
  config:
    activate:
      on-profile: "local"
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

springdoc:
  swagger-ui:
    url: ${LOCAL_BASE_URL}
