spring:
  application:
    name: Hrr Backend

  output:
    ansi:
      enabled: always

  profiles:
    group:
      local: "local"
      prod: "prod"
      test: "test"
    default: local

  #jpa
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

  jackson:
    time-zone: Asia/Seoul

  config:
    import: optional:env[.env]


  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs
    enabled: ${SWAGGER_ENABLED:true}   # 필요 시 프로필에서 덮어쓰기

#카카오 로그인
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me
  app-redirect-uri: ${KAKAO_APP_REDIRECT_URI:hrrapp://oauth/kakao}
  admin-key: ${KAKAO_ADMIN_KEY}

model:
  api:
    url: http://localhost:8000/recommend
    embedding-url: http://localhost:8000/embedding
    health-url: http://localhost:8000/

apple:
  team-id: ${APPLE_TEAM_ID}
  client-id: ${APPLE_CLIENT_ID}
  key-id: ${APPLE_KEY_ID}
  p8-key: ${APPLE_P8_KEY}

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

