spring:
  application:
    name: Hrr Backend

  output:
    ansi:
      enabled: always

  profiles:
    group:
      local: "local"
      dev: "dev"
      test: "test"
    default: local

  #jpa
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

  jackson:
    time-zone: Asia/Seoul

  config:
    import: optional:env[.env]

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs
    enabled: ${SWAGGER_ENABLED:true}   # 필요 시 프로필에서 덮어쓰기

