ALTER TABLE verification ADD COLUMN IF NOT EXISTS text_image1 VARCHAR(255) NULL;
ALTER TABLE verification ADD COLUMN IF NOT EXISTS text_image2 VARCHAR(255) NULL;
ALTER TABLE verification ADD COLUMN IF NOT EXISTS text_image3 VARCHAR(255) NULL;
